#!/usr/bin/env bash

# Run as developer user
[[ $(whoami) == 'developer' ]] || exec as-developer "$0" "$@";

# Exit on error
set -euo pipefail

# Ensure uploads directory (and all future subdirs) are writable by nginx
chmod    g+s "$CODE_BASE"/public/ext/uploads
chmod -R g+w "$CODE_BASE"/public/ext/uploads

# Install global tools, unless they're already part of the image
[[ "$COMPOSER_HOME" == /composer ]] || composer global install --no-dev

# Generate initial .lock if not present
[[ -f "$CODE_BASE/composer.lock" ]] || composer install --working-dir="$CODE_BASE" $COMPOSER_OPTIONS

cd "$CODE_BASE" && imposer apply
